_security_logout:
    resource: security.route_loader.logout
    type: service

## security:
##     # ... salut je m'appelle eliott
##     access_control:
##         - { path: ^/admin, roles: ROLE_ADMIN }