<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCGRICnz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCGRICnz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCGRICnz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCGRICnz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCGRICnz\App_KernelDevDebugContainer([
    'container.build_hash' => 'CGRICnz',
    'container.build_id' => '2d6814c3',
    'container.build_time' => 1738666811,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCGRICnz');
